{{- range .Values.bots }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curatedotfun.fullname" $ }}-{{ .name }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "curatedotfun.name" $ }}-{{ .name }}-secrets
    helm.sh/chart: {{ include "curatedotfun.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  dbPassword: {{ .dbPassword | b64enc }}
  encryptionKey: {{ .encryptionKey | b64enc }}
  postgresUser: {{ .postgresUser | b64enc }}
  postgresDB: {{ .postgresDB | b64enc }}
{{- end }}